### ISSUE TITLE
Graceful exit

### ISSUE THREAD

**Issue by ganeshmaharaj** [ganeshmaharaj/lvm-snapshotter#8]
https://medium.com/@kpbird/golang-gracefully-stop-application-23c2390bb212 <-- the blog talks about using channels to capture SIGINT and SIGKILL and gracefully exit the tool (we will unmount the metadata-db mount and remove the folder). Might be something for us to consider.

**Comment by sboeuf** [comment]
@ganeshmaharaj yes we do handle signals properly in other components such as `kata-proxy`, `kata-shim`. Take a look [here](https://github.com/kata-containers/proxy/blob/master/proxy.go#L463), [here](https://github.com/kata-containers/proxy/blob/master/proxy.go#L312-L347) and [here](https://github.com/kata-containers/proxy/blob/master/signals.go) for reference.

Just for correctness, we can handle `SIGINT` and `SIGTERM`, but `SIGKILL` is a special case since the process never receives it since the kernel is the one receiving it and killing the process without notice.
